servos:
  - name: gripper
    id: 1
    invert: false
    offset_pulse: 0
    degrees_min: 0
    degrees_max: 180
    pulse_min: 500
    pulse_max: 2500
  - name: wrist
    id: 3
    invert: false
    offset_pulse: 0
    degrees_min: 0
    degrees_max: 180
    pulse_min: 500
    pulse_max: 2500
  - name: elbow
    id: 4
    invert: false
    offset_pulse: 0
    degrees_min: 0
    degrees_max: 180
    pulse_min: 500
    pulse_max: 2500
  - name: shoulder
    id: 5
    invert: false
    offset_pulse: 0
    degrees_min: 0
    degrees_max: 180
    pulse_min: 500
    pulse_max: 2500
  - name: base
    id: 6
    invert: false
    offset_pulse: 0
    degrees_min: -90
    degrees_max: 90
    pulse_min: 500
    pulse_max: 2500

