black:
  max:
  - 39
  - 138
  - 135
  min:
  - 19
  - 118
  - 115
blue:
  max:
  - 106
  - 141
  - 95
  min:
  - 86
  - 121
  - 75
green:
  max:
  - 136
  - 90
  - 165
  min:
  - 116
  - 70
  - 145
red:
  max:
  - 101
  - 191
  - 175
  min:
  - 81
  - 171
  - 155
white:
  max:
  - 169
  - 136
  - 129
  min:
  - 149
  - 116
  - 109
