black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 110
  - 170
  - 200
  min:
  - 80
  - 130
  - 150
green:
  max:
  - 115
  - 140
  - 180
  min:
  - 60
  - 95
  - 150
red:
  max:
  - 60
  - 190
  - 80
  min:
  - 30
  - 160
  - 50
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
