black:
  max:
  - 89
  - 255
  - 255
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 100
  - 135
  - 130
  min:
  - 80
  - 120
  - 120
green:
  max:
  - 105
  - 135
  - 132
  min:
  - 90
  - 132
  - 128
red:
  max:
  - 200
  - 150
  - 150
  min:
  - 80
  - 120
  - 90
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
