# Kinematics configuration for ArmPi Mini
manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematics
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  kinematics_solver_research_resolution: 0.01
  kinematics_solver_research_attempts: 5

arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematics
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  kinematics_solver_research_resolution: 0.01
  kinematics_solver_research_attempts: 5

gripper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematics
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3 